# buildType will be discovered
# - pom.xml -> maven
# - build.gradle -> gradle
# - default -> command: bash command provided (e.g. mvn clean install -Dmaven.test.skip)
pipeline:
  suit: service-simple
  service: ${repo}

services:
  - name: default
    buildType: maven
    orchestration: k8s
    description: default service will be merged with all services that missing some required params
    release:
      - vcs
      - docker
